export const LOAD_ALL_QUESTION = 'LOAD_QUESTION';
export const ALL_QUESTION_SUCCESS = 'ALL_QUESTION_SUCCESS';
export const ALL_QUESTION_FAILURE = 'ALL_QUESTION_FAILURE';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_FAILURE = 'POST_QUESTION_FAILURE';
export const SINGLE_QUESTION_SUCCESS = 'SINGLE_QUESTION_SUCCESS';
export const SINGLE_QUESTION_FAILURE = 'SINGLE_QUESTION_FAILURE';
export const SINGLE_QUESTION_LOADING = 'SINGLE_QUESTION_LOADING';
