export const CORRECT_ANSWER_SUCCESS = 'CORRECT_ANSWER_SUCCESS';
export const CORRECT_ANSWER_FAILURE = 'CORRECT_ANSWER_FAILURE';
export const POST_ANSWER_SUCCESS = 'POST_ANSWER_SUCCESS';
export const POST_ANSWER_FAILURE = 'POST_ANSWER_FAILURE';